// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import Footer from "@/components/footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "PRO Services Dubai - Professional Business Solutions",
  description: "Comprehensive business solutions including consulting, digital marketing, web development, legal services, and more in Dubai, UAE.",
  keywords: "business consulting, digital marketing, web development, legal services, Dubai, UAE, PRO Services",
  authors: [{ name: "PRO Services Dubai" }],
  openGraph: {
    title: "PRO Services Dubai - Professional Business Solutions",
    description: "Comprehensive business solutions including consulting, digital marketing, web development, legal services, and more in Dubai, UAE.",
    url: "https://proservices.ae",
    siteName: "PRO Services Dubai",
    locale: "en_US",
    type: "website",
    images: [
      {
        url: "https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/39b1baac-b494-4b4d-a8f4-bb8e52c31f50.jpg",
        width: 512,
        height: 512,
        alt: "PRO Services Dubai Logo",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "PRO Services Dubai - Professional Business Solutions",
    description: "Comprehensive business solutions including consulting, digital marketing, web development, legal services, and more in Dubai, UAE.",
    images: ["https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/39b1baac-b494-4b4d-a8f4-bb8e52c31f50.jpg"],
  },
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
      { url: "https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/39b1baac-b494-4b4d-a8f4-bb8e52c31f50.jpg", sizes: "512x512", type: "image/png" },
    ],
    apple: [
      { url: "https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/39b1baac-b494-4b4d-a8f4-bb8e52c31f50.jpg", sizes: "180x180", type: "image/png" },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <link rel="icon" href="/icon.svg" type="image/svg+xml" />
        <link rel="icon" href="https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/39b1baac-b494-4b4d-a8f4-bb8e52c31f50.jpg" type="image/png" sizes="512x512" />
        <link rel="apple-touch-icon" href="https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/39b1baac-b494-4b4d-a8f4-bb8e52c31f50.jpg" sizes="180x180" />
        <meta name="theme-color" content="#1B2951" />
      </head>
      <body
        className={`${inter.variable} ${poppins.variable} font-inter antialiased bg-[#F7FAFC] dark:bg-[#0B1220] text-[#0B1220] dark:text-[#F1F5F9] min-h-screen`}
      >
        <ThemeProvider>
          <div className="flex flex-col min-h-screen">
            <Header />
            <main className="flex-1">
              {children}
            </main>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}